name = "webauth"
type = "javascript"

# This field specifies that the Worker will be deployed to a *.workers.dev domain.
workers_dev = true
# -- OR --
# These fields specify that the Worker will deploy to a custom domain.
# zone_id = "your-zone-id"
# routes = ["example.com/*"]


# You need to configure these 2 KV namespaces before publishing.
kv_namespaces = [
    { binding = "AUTH", id = "" },
    { binding = "SESSIONS", id = "" }
]
